#@data/values
---
#@ default_stacks = ['cflinuxfs3']

supported_languages:
- name: binary
  stacks: #@ default_stacks + ["windows2016", "windows"]
- name: dotnet-core
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: go
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: java
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: nginx
  stacks: #@ default_stacks
- name: nodejs
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: php
  stacks: #@ default_stacks
- name: python
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: r
  stacks: #@ default_stacks
- name: ruby
  stacks: #@ default_stacks
- name: staticfile
  stacks: #@ default_stacks
supported_languages_without_java:
- name: binary
  stacks: #@ default_stacks + ["windows2016", "windows"]
- name: dotnet-core
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: go
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: nginx
  stacks: #@ default_stacks
- name: nodejs
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: php
  stacks: #@ default_stacks
- name: python
  stacks: #@ default_stacks + ["cflinuxfs4"]
- name: r
  stacks: #@ default_stacks
- name: ruby
  stacks: #@ default_stacks
- name: staticfile
  stacks: #@ default_stacks
